<?php
/**
 * @file
 * A module that runs code to turn on all other contrib/custom modules.
 */

/**
 * @function
 * Implements hook_update_N().
 * Enables the following contrib modules:
 * backup_migrate, ctools, date, devel, features, features_extra, pathauto,
 * strongarm, token, views, webform
 */

/** Method 1 */
function acs_master_update_N() {
  // Create an array listing all module names
  $modules = array(
    'backup_migrate',
    'date',
    'devel',
    'features',
    'features_extra',
    'pathauto',
    'strongarm',
    'views',
    'webform'
  );
  // Enable each module in the array
  foreach ($modules as $module_name) {
    module_enable($module_name, TRUE);
  }
}
/** Method 2 */
  function acs_master_update_N() {
    // Directly enable each module 1 at a time
    module_enable(backup_migrate, TRUE);
    module_enable(date, TRUE);
    module_enable(devel, TRUE);
    module_enable(features, TRUE);
    module_enable(features_extra, TRUE);
    module_enable(pathauto, TRUE);
    module_enable(strongarm, TRUE);
    module_enable(views, TRUE);
    module_enable(webform, TRUE);
  }

